service: darknetchat-inviter

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - docs/**
    - node_modules/serverless-prune-plugin/**
    - .circleci/**

functions:
  darknetchat-inviter:
    name: darknetchat-inviter
    description: Invite folks to darknet chat on Slack
    handler: index.inviter
    environment:
      SLACK_TOKEN: ${env:SLACK_TOKEN}

    events:
      - http:
          path: /
          method: get
          cors: true

# Clean up older versions of the function; keep around
# the last for rollback, just in case
custom:
  prune:
    automatic: true
    number: 1

plugins:
  - serverless-prune-plugin
